### ISSUE TITLE
Imported data causing Map page to fail

### ISSUE THREAD

**Issue by andrewvaughan** [gramps-project/gramps-web#337]
I imported GED data from another application, which seems to have worked swimmingly, except something is causing the **Maps** page to fail.

The error in the console when loading the map is:

```
Uncaught (in promise) Error: Invalid LatLng object: (NaN, NaN)
    at new Lp (3124eda5.js:3456:7237)
    at J.updated (3124eda5.js:3468:1699)
    at J._$AE (3124eda5.js:2:6340)
    at J.performUpdate (3124eda5.js:2:6120)
    at J.scheduleUpdate (3124eda5.js:2:5702)
    at J._$EC (3124eda5.js:2:5610)
```

I looked through all of my `Places` and there doesn't seem to be anything malformed in there; however, there are definitely informal places in the list that would likely result in a `null` search result from any API being used to look up lat/long.

My guess is that the Maps feature does not adequately manage when lat/long return `NaN` - my guess from a `parseFloat` or similar call. When this occurs, the entire Maps page fails to load, as JS execution halts.

**Comment by pieper** [comment]
I'm seeing this error too, but with a different stack trace:

```
bfd5d431.js:4573 Uncaught (in promise) Error: Invalid LngLat object: (NaN, NaN)
    at new hh (bfd5d431.js:4573:309668)
    at hh.convert (bfd5d431.js:4573:310261)
    at ze.handleEaseTo (bfd5d431.js:4573:629848)
    at t.Map.easeTo (bfd5d431.js:4573:832634)
    at t.Map.panTo (bfd5d431.js:4573:828248)
    at SN.updated (bfd5d431.js:4713:1992)
    at SN._$AE (bfd5d431.js:2:6446)
    at SN.performUpdate (bfd5d431.js:2:6308)
    at SN.scheduleUpdate (bfd5d431.js:2:5779)
    at SN._$ET (bfd5d431.js:2:5687)
```

My data came from ancestry via gramps desktop XML.  Is there anything I can do to clean it up or does this need to be fixed in the javascript code?

**Comment by DavidMStraub** [comment]
When exactly do you see this? On loading the map or when selecting a point?

**Comment by DavidMStraub** [comment]
I just found & fixed one possible case where a division by zero could have occurred. You can try the `latest-devel` image to test it.

**Comment by pieper** [comment]
Great, thank you @DavidMStraub!  Is there a way I can test on grampshub? (I don't currently have a docker setup, but I could if that's the best way to test).

To answer your question it happens when I enter the map page.  The map appears but no pins show up.

**Comment by DavidMStraub** [comment]
>  Is there a way I can test on grampshub?

No, you'll have to wait for the next release to be deployed.

**Comment by DavidMStraub** [comment]
I assume this is fixed.
