### ISSUE TITLE
500 error when viewing a place with a deleted encloser

### ISSUE THREAD

**Issue by vpier111** [gramps-project/gramps-web#381]
Steps to Reproduce:
1. Create a place
2. Add an encloser
3. Delete said encloser
4. Try to view previously enclosed place
5. Error 500

**Comment by vpier111** [comment]
This also prevents viewing of the map; Same Error 500 banner is shown on the bottom and place markers do not appear.

**Comment by DavidMStraub** [comment]
Please share your version info and see https://github.com/gramps-project/gramps-web-api/issues/471.

**Comment by vpier111** [comment]
> Please share your version info and see [gramps-project/gramps-web-api#471](https://github.com/gramps-project/gramps-web-api/issues/471).

I am using Gramps Hub.

**Comment by DavidMStraub** [comment]
... which is 
```
Gramps 5.1.6
Gramps Web API 1.5.1
Gramps Web Frontend 24.1.2
locale: en
multi-tree: true
task queue: true
```

**Comment by DavidMStraub** [comment]
Is the error still present with Gramps Web API 1.6.0?

**Comment by EvilCartyen** [comment]
I think I have this issue now - all attempts to look at the map results in error 500 in the bottom left corner.

Error log shows:

`
[2025-01-28 07:50:57 +0000] [14] [ERROR] Error handling request /api/places/?locale=en&profile=self&backlinks=1
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/auth.py", line 44, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/webargs/core.py", line 657, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/base.py", line 464, in get
    [self.full_object(obj, args, locale=locale) for obj in objects],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/base.py", line 464, in <listcomp>
    [self.full_object(obj, args, locale=locale) for obj in objects],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/base.py", line 96, in full_object
    obj = self.object_extend(obj, args, locale=locale)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/places.py", line 48, in object_extend
    obj.profile = get_place_profile_for_object(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/util.py", line 390, in get_place_profile_for_object
    _place = db_handle.get_place_from_handle(handle)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps/gen/db/generic.py", line 1356, in get_place_from_handle
    return self._get_from_handle(PLACE_KEY, Place, handle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps/gen/db/generic.py", line 1341, in _get_from_handle
    raise HandleError("Handle %s not found" % handle)
gramps.gen.errors.HandleError: Handle fcbfe476eb32f558267075942b7 not found
`

**Comment by EvilCartyen** [comment]
System information:

Gramps 5.2.4
Gramps Web API 2.8.0
Gramps Web Frontend 24.12.2
Gramps QL 0.3.0
Sifts 1.0.0
locale: en
multi-tree: false
task queue: true
OCR: true
chat: false

**Comment by EvilCartyen** [comment]
Well then - I found your neat DB repair tool in the Administration and it worked perfectly... lovely!
